name: qjay
description: "Q-Jay audio player"
publish_to: 'none'
version: 1.1.2+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^7.0.0
  cryptography: ^2.5.0
  device_info_plus: ^12.2.0
  ffi: ^2.1.3
  fixnum: ^1.1.1
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  multicast_dns: ^0.3.3
  permission_handler: ^12.0.1
  protobuf: ^5.0.0
  provider: ^6.0.5
  shimmer_animation: ^2.1.0
  universal_ble: ^1.1.0
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/icons/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: assets/icons/icon_android.png
  image_path_ios: assets/icons/icon_ios.png
  ios: true

flutter:
  uses-material-design: true

  fonts:
  - family: QJay
    fonts:
      - asset: assets/icons/QJay.ttf

  - family: Exo
    fonts:
      - asset: assets/fonts/exo/Exo-Thin.ttf
        weight: 100
      - asset: assets/fonts/exo/Exo-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/exo/Exo-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/exo/Exo-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/exo/Exo-Light.ttf
        weight: 300
      - asset: assets/fonts/exo/Exo-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/exo/Exo-Regular.ttf
        weight: 400
      - asset: assets/fonts/exo/Exo-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/exo/Exo-Medium.ttf
        weight: 500
      - asset: assets/fonts/exo/Exo-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/exo/Exo-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/exo/Exo-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/exo/Exo-Bold.ttf
        weight: 700
      - asset: assets/fonts/exo/Exo-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/exo/Exo-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/exo/Exo-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/exo/Exo-Black.ttf
        weight: 900
      - asset: assets/fonts/exo/Exo-BlackItalic.ttf
        weight: 900
        style: italic

  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
